### ISSUE TITLE
Dartlang's Dependency Hell

### ISSUE THREAD

**Issue by hpoit** [montyr75/dart_chat_ng_fb_start#1]
Hi! Thanks for putting this project up. What should I do about
![image](https://user-images.githubusercontent.com/3711100/60972902-8434f700-a2fd-11e9-9512-c29d7d4a253d.png)

**Comment by montyr75** [comment]
Hi! Yes, there are a number of things that are pretty out of date in that project. It's several years old, and it was built using Dart 1.x and AngularDart 4.0. To work again, it would need to be migrated to Dart 2.x and AngularDart 5+. It may also need updates to its Firebase code at this point.

Your best bet is to start a new AngularDart project (using `stagehand` or your IDE) , then slowly bring code from the chat project into yours, fixing things as you go. That's how I would update it, myself. Unfortunately, there are no plans to update it, because I have moved my development entirely to Flutter now, and I'll be relying on Flutter for Web to produce web apps. Flutter provides a very different approach to app creation.

I do love the AngularDart experience compared to Angular with TypeScript, but I think Flutter is the future. Good luck!

**Comment by Fugazi56** [comment]
Monty, I would prefer to build a PWA in flutter too, but I understand Flutter for web isn't ready yet. Are you having success with using Flutter for web?

**Comment by montyr75** [comment]
> Monty, I would prefer to build a PWA in flutter too, but I understand Flutter for web isn't ready yet. Are you having success with using Flutter for web?

I am having success with Flutter for Web, despite its beta status, yes. For now, I'm keeping my expectations low and dealing with the inevitable issues as they arise. Lots of my projects are small and undemanding, so those work all right. The few very serious ones I'm doing won't be complete for months, so I expect many of the beta issues to be resolved in that time. If you can afford to be patient, it's certainly a great idea to be ahead of the curve with Flutter.
